"""
Convert a PNG emoji image to a TFT_eSPI-compatible RGB565 PROGMEM header.

Usage:
    pip install Pillow
    python emoji_to_progmem.py <input.png> <output.h> [--size 48]

The output header defines:
    const uint16_t <SYMBOL>_ICON[W * H] PROGMEM = { ... };
    const int      <SYMBOL>_ICON_W = W;
    const int      <SYMBOL>_ICON_H = H;

Bytes are stored in host (little-endian) RGB565 order — use tft.setSwapBytes(true)
before pushImage, same as the app icon pipeline in assignments.cpp.

Recommended source for Noto Emoji PNGs (72px, no login needed):
  https://github.com/googlefonts/noto-emoji/tree/main/png/72
Download the 🔇 file: emoji_u1f507.png (MUTE speaker)
Then run:
  python emoji_to_progmem.py emoji_u1f507.png ../mixer/mute_icon.h --size 48 --symbol MUTE
"""

import argparse
import struct
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow not installed — run: pip install Pillow")


def rgb888_to_rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def convert(src: Path, dst: Path, size: int, symbol: str) -> None:
    img = Image.open(src).convert("RGBA").resize((size, size), Image.LANCZOS)

    pixels: list[int] = []
    for y in range(size):
        for x in range(size):
            r, g, b, a = img.getpixel((x, y))
            # Blend onto black background using alpha
            r = (r * a) // 255
            g = (g * a) // 255
            b = (b * a) // 255
            pixels.append(rgb888_to_rgb565(r, g, b))

    guard = dst.stem.upper().replace("-", "_") + "_H"
    lines = [
        f"#pragma once",
        f"#include <Arduino.h>",
        f"",
        f"// Auto-generated by emoji_to_progmem.py — do not edit by hand.",
        f"// Source: {src.name}  →  {size}×{size} px, RGB565 host-endian (use setSwapBytes(true)).",
        f"",
        f"static const int {symbol}_ICON_W = {size};",
        f"static const int {symbol}_ICON_H = {size};",
        f"",
        f"static const uint16_t {symbol}_ICON[{size * size}] PROGMEM = {{",
    ]

    # 8 values per line for readability
    row: list[str] = []
    for i, v in enumerate(pixels):
        row.append(f"0x{v:04X}")
        if len(row) == 8:
            lines.append("  " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("  " + ", ".join(row) + ",")

    lines += ["};", ""]

    dst.write_text("\n".join(lines), encoding="utf-8")
    print(f"Written {dst}  ({size}×{size}, {len(pixels)} pixels)")


def main() -> None:
    ap = argparse.ArgumentParser(description="PNG → RGB565 PROGMEM header")
    ap.add_argument("input",  type=Path, help="Source PNG")
    ap.add_argument("output", type=Path, help="Destination .h file")
    ap.add_argument("--size", type=int, default=48, help="Output size in pixels (default 48)")
    ap.add_argument("--symbol", default="MUTE", help="C symbol prefix (default MUTE)")
    args = ap.parse_args()

    if not args.input.exists():
        sys.exit(f"Input file not found: {args.input}")

    convert(args.input, args.output, args.size, args.symbol)


if __name__ == "__main__":
    main()
